# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d2642c2ddb4296dc12d7fd7210d8e8c929af37a04c9ee31d647411a2422357ea1d02b7cbd0f9e0944cf4ca9a24c10acc05b9a8f6ef7cf74e95787e450be10e

test:
  secret_key_base: 56dff07ea52622b7084dbcc48670ca00f5f8296d8493a25102ed8e56c49730897771b6176bda9673d6a40ef80a60d3c714a3e8f42c6b481cc588d7429371ce0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
